controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /accueil
    controller: App\Controller\HomeController::bonjour

routeRedirect:
    path: /routeRedirect
    controller: App\Controller\HomeController::routeRedirect

redirect:
    path: /redirect
    controller: App\Controller\HomeController::redirect302

template:
    path: /template
    controller: App\Controller\HomeController::template
